name: "название шаблона"
description: "описание шаблона"
title: "[Ошибка]:"
labels: ["bug"]
body:
  - type: textarea
    id: ger
    attributes:
      label: "подпись поля"
      description: "описание"
      placeholder: "подсказка"
    validations:
      required: true
